### ISSUE TITLE
Just a thought!

### ISSUE THREAD

**Issue by t-o-m-h** [blopker/superduper#27]
Hey, so cool what you’ve done! I was looking into buying the bike but wanted to make sure something like this exists before going ahead. I have a couple of questions/thoughts- 
- For the European bikes would it be possible to add a setting to switch countries so the Class-2 defaults to 20mph instead of 15mph? 
- You said in the FAQs the setting lock tells SD to ignore the bike settings if the app is open. For an iPhone when you say open do you mean it is the current app in use, or just open in the background and not swiped away and fully closed? 
Thanks so much.

**Comment by t-o-m-h** [comment]
Sorry, looks like you’ve already covered this in the closed tickets!

**Comment by blopker** [comment]
Hey! Thanks for using SD 😄. But yeah, the app doesn't have any control on how the different classes are defined, just what class the bike is on. All the class info is stored in the bike itself. As for the lock, only Android has 'Background Lock' due to iOS limitations. If the settings are locked on iPhone you'll need to flick the app open, but then it will automatically connect and update the settings for you.

**Comment by t-o-m-h** [comment]
Thanks a lot for explaining all of that. As soon as I come across anything I can feedback on I will send a message! Really appreciate what you've done.

**Comment by t-o-m-h** [comment]
Thanks a lot for explaining all of that. As soon as I come across anything I can feedback on I will send a message! Really appreciate what you've done.
