### ISSUE TITLE
Not finding Z-Miami (Z1.2)

### ISSUE THREAD

**Issue by Atticaz** [blopker/superduper#28]
The SuperDuper app is not finding my Z-Miami (Z1.2) or my wife’s. I have BT enabled and allowed on both my iPhone 14pro Max and for the App.

**Comment by blopker** [comment]
Hey! Thanks for trying the app out. If you haven't tried the FAQ section yet, I'd start there. Note that only one app and phone can be connected to a bike at a time. Sometimes another phone is already connected, or even another app on the same phone running Superduper.

**Comment by Atticaz** [comment]
> Hey! Thanks for trying the app out. If you haven't tried the FAQ section (https://github.com/blopker/superduper?tab=readme-ov-file#faq) yet, I'd start there. Note that only one app and phone can be connected to a bike at a time. Sometimes another phone is already connected, or even another app on the same phone running Superduper.

No other phones have this app. I am the first in this house. Just can’t get the bike to show up in the app.

**Comment by stabas** [comment]
I have the same issue. Freh new Bike. Z Adventure. Tried to connect it to the SuperDuper App but it wont find it.

**Comment by blopker** [comment]
Another tip I just saw: Make sure the bike is on the latest firmware (the torque update). I looks like some bikes are on firmware too old for Superduper. There's also the Walker73 app if you're on Android. Might be worth trying out. Other tips are: Uninstall the official app and restarting the phone.

But yeah, this is hard to debug since SD doesn't have any analytics on it for privacy. I don't have any data or error collection I can access.

**Comment by blopker** [comment]
Also! If anyone is in the San Francisco area and is willing to let me take a look, I'd be happy to see if I can learn more. I've never personally tested on a Z1.

**Comment by Bamuel** [comment]
I will give it a test on a Z1 Adventure & Z1 Miami (EU bike) in Australia when I get the chance and let you know.
But it sounds like a bike firmware update might resolve it.

**Comment by stabas** [comment]
What worked for me was turning on location for the first time of connecting!
