### ISSUE TITLE
Support for the S2

### ISSUE THREAD

**Issue by Syb3rnetix** [blopker/superduper#6]
Bike: Super73 S2 EU
Controller version: 410
Phone: iPhone 13
Operating System: iOS 16.1.2
App version: 0.0.17

When auto connecting to the bike on first launch the app goes into mode 4 and PAS 4 but these settings do not reflect the mode or PAS level on the bike (defaults to mode 1, PAS 0). If you modify the PAS on the app it does nothing, but on the bike it does. If you change 
the mode on the app it does change but now only goes from 0 to 3.

![F3FA6306-B933-49C9-BF7D-07424E909100](https://user-images.githubusercontent.com/122878219/213733967-8d3d47c1-0c97-4929-acdd-5dcac4c0ff72.png)

**Comment by Syb3rnetix** [comment]
> That's interesting. The S2 must have a slightly different internal state than the RX, which is confusing the app. I wish I had access to an S2 to test. Although, I don't even know how the app would be able to differentiate between the two models without being told by the user.
> 
> If you're up for it, we could hop on a call next week and I could walk you through the steps to get the data I need to make this work. You'll need a way to get a Mac computer close enough to your bike for a Bluetooth connection to be established.

I might not be able to since I do not have access to a Apple Mac. I will have to see if I can figure something out and get access to MacOS.

**Comment by JacopoV** [comment]
Hi there! 
Considering i ve an S2 too, i can offer my time to help. 
Laptop : Macbook Pro M1 
Phone : Google Pixel 7 Pro + Pixel Watch 😉

**Comment by JacopoV** [comment]
@blopker Hi, i mean, i can give support for the issue on the S2 using a MacBook Pro. In case you need some debug/test via BT :)

**Comment by mbaran5** [comment]
I also have access to iOS device as well as a MBP with xcode and developer tools if needed. I have a US S2

**Comment by blopker** [comment]
Thanks for all the support everyone! I'll post here what is needed, or at least how I got the information. Please let me know if you try and are unable to follow. I'll add more context as required.

I have a Mac with an Android phone (weird, I know!). However, this should work on any desktop OS. I think you may need an Android phone though. I don't know the process on iOS, yet.

First an overview of the process. 

Essentially, the contractors who made the app left debug logs enabled on the official Android (and maybe iOS) app. So, we need to get the logs while running the official app. The idea is to connect your computer to your phone using `adb`, use your phone to connect to the bike using the official app, then fire off some commands and record what the app puts out. The critical info will look like HEX codes (0x487127), it's the raw data the app is sending to the bike. If I get those codes, annotated with what command you send at the time, I'll be able to reverse engineer what is needed.

Rough steps look like:

1. Download and install `adb`: https://developer.android.com/studio/command-line/adb
1. Connect phone to computer using `adb`, get the stream of system logs.
1. Connect phone to bike
1. Blast bike with a few commands from the app, recording what commands you send with what logs show up
1. Send me the logs :)

Again, there may be a similar process with iOS, but I'm not sure.

**Comment by JacopoV** [comment]
@blopker  do you have a specific command to log? I tried to log only for you package io.kbl.superduper but it's spitting out a lot of stuff :) it's correct ? 
adb logcat | grep -F "`adb shell ps | grep io.kbl.superduper  | tr -s [:space:] ' ' | cut -d' ' -f2`"

**Comment by blopker** [comment]
Ah, sorry, the app to log is the official app, not SD. But yeah, it's going to be a bit verbose in any case. Filtering to the specific app package is the right call.

**Comment by JacopoV** [comment]
@blopker here it is 👍 
[s2log.txt](https://github.com/blopker/superduper/files/10519585/s2log.txt)

////// INSTRUCTIONS GIVEN AFTER CONNECTION 
Mode selection 2
Lights on
Lights off
Mode selection 4
Mode selection 3
Mode selection 1

**Comment by JacopoV** [comment]
I also tested by having SuperDuper in the background with the auto lock on, and indeed i do see sideeffects on the bike, but with weird numbers (not range from 1 to 4) and not even mapped ( SuperDuper says mode 1 is basically equivalent to Super73 mode 2) .
Haven't got the possibility to try yet SuperDuper on the road but i ll give it a try tomorrow, to see if it set values correctly and inputs them once the bike is turned on/off .
Thanks for you help!

**Comment by Syb3rnetix** [comment]
Just to confirm, did you only do the modes or did you mean PAS levels? the modes work on S2; it was the PAS levels that were broke. Anyways legend for doing this! thank you :)

**Comment by JacopoV** [comment]
Oh lord, sorry.. i totally forgot because i skipped my 78th coffee of the day. 
Here's another one with PAS levels 💯 
[s2log_pas1-4.txt](https://github.com/blopker/superduper/files/10519641/s2log_pas1-4.txt)

Used the handle bar controller, moving from PAS 0 to 4 and viceversa. I hope you can see some stuff

**Comment by JacopoV** [comment]
Uploading again the log with PAS changed from 0 to 4 and viceversa from the handle bar. 
[s2log_pas1-4.txt](https://github.com/blopker/superduper/files/10520639/s2log_pas1-4.txt)

**Comment by blopker** [comment]
Awesome. Here's the relevant data:
```
0000155f-1212-efde-1523-785feabcd123:00D10004040000000000:WRITE
0000155f-1212-efde-1523-785feabcd123:00D10104040000000000:WRITE
0000155f-1212-efde-1523-785feabcd123:00D10004040000000000:WRITE
0000155f-1212-efde-1523-785feabcd123:00D10004050000000000:WRITE
0000155f-1212-efde-1523-785feabcd123:00D10104050000000000:WRITE
0000155f-1212-efde-1523-785feabcd123:00D10004050000000000:WRITE
0000155f-1212-efde-1523-785feabcd123:00D10004070000000000:WRITE
0000155f-1212-efde-1523-785feabcd123:00D10004060000000000:WRITE
0000155f-1212-efde-1523-785feabcd123:00D10004040000000000:WRITE
```
The format is SERVICE:DATA:OPERATION. The entire state is sent over with each WRITE command. So, you can see mode changing in the 10th data column (5th byte), and the light (1 or 0) changing in the 6th (3rd byte).  The 04 at byte 4 is likely the assist level since that's what it is on the other models as well. Indeed, it looks like the S2 modes are 4-7 internally, where the R/RX is 0-3. This is why the app is causing weirdness on S2s. I should be able to get a test app out next week for people to try out :) Thanks @JacopoV!

**Comment by blopker** [comment]
The other part of this is how to either detect the S2 model, or at least how to let people select the model they have. As far as I can tell in the official app they have a database that maps bike serial numbers to model. We don't really have access to that. I don't know if there's a way for the bike to tell us that info directly.

**Comment by mbaran5** [comment]
does the bike broadcast data back to the app via bluetooth? Maybe an onboarding step could be to have the user toggle the headlight on/off and look for the byte that differs between S and R/RX?

**Comment by JacopoV** [comment]
@blopker thanks to you! 
To reduce complexity, to see if it's working, for now it's probably best to leave the bike type selection up to the user, to pick from S2 or R or RX. 😁

Ping me please when you have a new release so I can give a try 🎉

**Comment by blopker** [comment]
It does. You can see in the logs were every data that starts with `0300` is the bike updating the app. The thing is that all the other data besides mode looks exactly the same. I'm not sure why assist would not be working, mode is? Unless were talking about different terms?

**Comment by mbaran5** [comment]
The app wasn't able to control my S2s headlight when I experimented with it yesterday, which is why I had mentioned that. I didn't try PAS or Mode since I am not updated and didn't want to have to open the official S73 app and risk being forced the update just yet.

**Comment by JacopoV** [comment]
@blopker hi! I finally had the chance to give a try on my S2... But something it's really off.

Bike: Super73 S2 EU
Controller version: 410
Phone: Pixel 7 Pro
Operating System: Android 13
App version: 0.0.17

When i set in SuperDuper mode 1 (afaik equivalent of the mode 2 from Super73 app) for some reason so the throttle is active.
Even worse, even if the top speed seems capped to 35kmh (it seems a bit more of the 32kmh on Super73 app), the power output it's just insane. It seems like the full unlocked watts. A bit dangerous because caught me off guard. 
Also if coming back in the official app, the mode seems set to be -2.

Any chance something is off like the PAS Internal codes? Can you please look into?
Many thanks 🙏

**Comment by blopker** [comment]
Hey everyone, wanted to update on this. I've fixed a few minor issues in the app, like changing the mode numbers from 0-3 to 1-4 and the Android version will now not kill the app when the screen is off. This change, however, is requiring me to do a bit of an architecture change, so it's taking a little longer than I'd hoped. This is next though!

**Comment by Chris7ophe** [comment]
Thank you 🙏 It’s really appreciated Regards,ChristopheOp 2 feb. 2023 om 19:53 heeft Bo Lopker ***@***.***> het volgende geschreven:﻿
Hey everyone, wanted to update on this. I've fixed a few minor issues in the app, like changing the mode numbers from 0-3 to 1-4 and the Android version will now not kill the app when the screen is off. This change, however, is requiring me to do a bit of an architecture change, so it's taking a little longer than I'd hoped. This is next though!

**Comment by JacopoV** [comment]
Thanks a lot @blopker for looking into! Really appreciated !

**Comment by blopker** [comment]
I just heard another S2 owner doesn't have any issues with the app as it is. Is everyone here on the latest firmware update? Meaning the torque update, I think.

**Comment by mbaran5** [comment]
I am not, so that is a good point. I was holding off until I knew this app worked so I could avoid using their app.

**Comment by JacopoV** [comment]
@blopker are you referring to my message regarding having a lot of torque and the throttle being available?
Because I just did a new test. In mode 2 (latest app) throttle is available.
But.. mode 3 is off and then mode 4 back on.
It seems following the US modes and not EU ones..

**Comment by blopker** [comment]
Ooooh, that's interesting. So maybe it's an EU vs US regulation thing and not a model support issue?

**Comment by Chris7ophe** [comment]
If you need me to test the EU version on iOS or android I can help, have
both. Bike is an RX.

Op vr 3 feb. 2023 om 19:55 schreef Bo Lopker ***@***.***>

**Comment by JacopoV** [comment]
@blopker it could be.. i have no clue to br honest 😅 but the throttle activation follows exactly the US ones. 
Bike has been bought in EU, but all of them are produced in Cali.
Just another thing, maybe other S2 users can check (maybe it's nothing). In the vehicle tab of S73 app , where all Infos are (BT version , serial and such) my bike is identified as model as RX . Never been an issue tho, but i always wondered why not S2.

**Comment by blopker** [comment]
OK! It was a bit of work to make this happen since I had to rearchitect the app and actually think about the data models, instead of the spaghetti code I hacked together originally, but this is ready to test! The cool thing is the code is now cleaner, and I was able to also add the ability to rename the bike as well. All good.

Anyway, the beta for Android will be ready after Google approves it in a few days. I'll announce here when that happens. If all goes well I'll put that and the iOS version in production for everyone!

Full changelog here: https://github.com/blopker/superduper/releases/tag/v0.0.21%2B21

**Comment by blopker** [comment]
For Android, to enroll in the test tracks, use https://play.google.com/apps/testing/io.kbl.superduper in your web browser. Version `0.0.21` is the version with the EU support.

**Comment by JacopoV** [comment]
@blopker thanks a ton for all your hard work! Really appreciates 🙏

I haven't fully tested it yet because outside is snowing as hell but i run some tests from the beta version:
- bike applies all PAS correctly and EU modes (eu model choosen) and they're marching perfectly and in real time the values in Official s23 app 💯
- on the kickstand i tried to pedal a second to compare the Power output/torque compared to the Official app and now it seems matching the expected and correct behaviour ✅

I ll try to test it fully on the road as soon as i can, but so far everything seems perfect. Matching exactly the EU modes values automatically solved the engine Power output (vad mentioned few weeks ago, by having weird numbers on the Official app, the engine was going nuts).

I should be able to test soon when the throttle is available or not according to the EU modes, but i m pretty confident that all works now.

Again, thabsk a lot for your time and effort put into this app ❤️

**Comment by blopker** [comment]
Fantastic. Thanks for testing, and providing the data! I've added some polish to the styles in 0.0.22, which I've just sent off for review. Should hit production in a few days! I'll also send off the iOS version as well. 

I'll leave this open for a few days to make sure we're all good.

**Comment by blopker** [comment]
Aaaaaand the iOS version is live!

**Comment by JacopoV** [comment]
So far so good @blopker . On S2 EU throttle works only with mode 4 as expected and everything else appears working completely! 
Thanks a lot again 🤠

**Comment by blopker** [comment]
Awesome, I'll close this out for now, but I'll see any additional comments if there are any issues!
